---
- name: Print post-hook variables
  hosts: localhost

  tasks:
  - name: Print managed-cluster-info
    ansible.builtin.debug:
      msg: This is cluster_info {{ cluster_info }}
  - name: Print managed-cluster-info
    ansible.builtin.debug:
      msg: This is cluster_deployment {{ cluster_deployment }}
  - name: Print managed-cluster-info
    ansible.builtin.debug:
      msg: This is install-config {{ install-config }}
