---
- name: Print post-hook variables
  hosts: localhost

  tasks:
  - name: Show managed-cluster info
    ansible.builtin.debug:
      msg: This is cluster_info {{ cluster_info }}
    when: cluster_info is defined
    
  - name: Show install-config info
    ansible.builtin.debug:
      msg: This is install-config {{ install-config }}
    when: install-config is defined

  - name: finish
    debug:
      msg: "Job is finished."
